services:
  game:
    build:
      context: .
      dockerfile: Dockerfile.dedicated
    command: [
      "Build/render_scene_file",
      "data",
      "data/levels/main/main.scn.json",
      "--app_reldir", ".vanilla_rally",
      "--print_render_residual_time",
      "--remote_site_id", "42",
      "--udp_ip", "0.0.0.0",
      "--udp_port", "8042",
      "--http_ip", "0.0.0.0",
      "--http_port", "8082",
      "--flavor", "extended"
    ]
    environment:
      LD_LIBRARY_PATH: Build
      REMOTE_IP: "${REMOTE_IP}"
      REMOTE_SECRET: "${REMOTE_SECRET}"
    volumes:
      - ./data:/app/data:ro
      - ./private:/app/private:ro
      - ./public/server:/app/public/server:ro
      - ./public/client:/app/public/client:ro
      - ./Mlib/E32URelease/Bin:/app/public/game:ro

  wt-udp-proxy:
    build:
      context: Mlib/Web_Transport_Udp
    ports:
      - "8443:443/udp" # WebTransport/HTTP/3 requires UDP
      - "8443:443/tcp" # TCP required for initial HTTP handshake
    environment:
      TARGET_UDP_HOST: "game"
      TARGET_UDP_PORT: "8042"
      WT_VERBOSE: "0"
      REMOTE_SECRET: "${REMOTE_SECRET}"
    volumes:
      - ./certs:/etc/ssl/certs

  nginx-proxy:
    # Built natively for rootless environments
    image: docker.io/bitnami/nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
    environment:
      REMOTE_SECRET: "${REMOTE_SECRET}"
      NGINX_ENVSUBST_FILTER: "REMOTE_SECRET"
    volumes:
      - ./nginx.conf.template:/tmp/default.conf.template:ro,U
      - ./bitnami_nginx_config:/opt/bitnami/nginx/conf/server_blocks:rw,U
      - ./certs:/etc/nginx/certs:ro,U
    command: >
      /bin/bash -c "
      envsubst '$$REMOTE_SECRET' < /tmp/default.conf.template > /opt/bitnami/nginx/conf/server_blocks/default.conf &&
      /opt/bitnami/scripts/nginx/run.sh
      "
